### ISSUE TITLE
all https://site.com   response none

### ISSUE THREAD

**Issue by dunkan02** [kennethreitz/grequests#114]
Hi. Why all  **https**  site return none.
**http** site response <Response [200]>
Simple code:
```
urls = [
    'http://google.com',
    'https://google.com',
]
rs = (grequests.get(u) for u in urls)
grequests.map(rs)
```
[<Response [200]>, None]

I have python 3.6.1 and modules:
C:\Users\woker>pip freeze
certifi==2017.4.17
chardet==3.0.4
gevent==1.2.2
greenlet==0.4.12
grequests==0.3.0
idna==2.5
requests==2.18.1
urllib3==1.21.1

**Comment by majurg** [comment]
I am experiencing the same issue.

**Comment by Jaronloch2** [comment]
Any news for this issue? I have little to no hair now.
I have Python 2.7.12 and grequests 0.3.0

urls = ['https://www.somesite.com','https://www.somesite.com']
rs = (grequests.get(u, hooks = {'response' : catch_response}, auth=('adminauth', 'adminpass')) for u in urls)

All results are None.

**Comment by 27pirateking** [comment]
experiencing the same when the number of requests is large, @kennethreitz please look into this.

**Comment by spyoungtech** [comment]
There are a number of reasons why HTTPS may be broken for you. Though, none I can see that are directly related to grequests. It's hard to help if there's no indication of the root cause.

One thing you can try to do to get more information is to specify an exception handler and get the traceback/error message. That would be a great starting point for identifying a possible cause.

@27pirateking your issue may actually be related to #54
