### ISSUE TITLE
Asynchronous requests with session does not work

### ISSUE THREAD

**Issue by dthielking** [kennethreitz/grequests#119]
Hi,

I tried to request multiple URLs at the same time. I have to authenticate against the API URLs therefor I have a opened session object. If I set this session object as kwargs argument to grequests.get() requests taking a long time.

What I have done:
import grequests
response = (grequests.get(url, session=api_session_obj) for url in urls)
grequests.map(response, size=50)

If I do not use session=api_session_obj the requests seems to be really fast but I do not get all information out of the api because I am not authenticated.

Maybe I am doing something wrong here.

**Comment by spyoungtech** [comment]
Hi @dthielking thanks for the report. I'd like to do some more testing with this, but I am not sure that I'm convinced this is necessarily a problem with grequests.

There's a lot that could be going into play here... Consider that, in the case of not being authenticated, it doesn't take as much work for the webserver to return that response; it doesn't need to examine the content of your request, retrieve any data, or send any sizable content. It may even return a response without invoking any backend application. 

On the other hand, if your request is otherwise successful, the webserver has a lot more work to do and presumably the response content will be much larger.  Also consider that, some authentication methods send credentials every single request, which can add overhead as well. The API itself may also be throttling your requests, among other considerations.

Can you quantify `a long time`? How long does a single authenticated synchronous request take compared to a nonauthenticated request? What happens if you just make 2 requests using grequests, do you still see the problem? How about 10, or 20; does the time seem to scale reasonably for the connection pool size?

Doing some brief testing with sessions and basic authentication, I haven't been able to reproduce this issue. Maybe if you can provide more details about the authentication method or service I can find a way to reproduce it.
