### ISSUE TITLE
how to handle result after request?

### ISSUE THREAD

**Issue by 1c7** [kennethreitz/grequests#91]
``` python
import grequests

urls = [
    'http://www.heroku.com',
    'http://python-tablib.org',
    'http://httpbin.org',
    'http://python-requests.org',
    'http://fakedomain/',
    'http://kennethreitz.com'
]

rs = (grequests.get(u) for u in urls)
for one in rs:
    print(one)
```

result: 

```
<grequests.AsyncRequest object at 0x7ffb7ffc9b38>
<grequests.AsyncRequest object at 0x7ffb7b9bdc18>
<grequests.AsyncRequest object at 0x7ffb7ffc9b38>
<grequests.AsyncRequest object at 0x7ffb7b9bdc18>
<grequests.AsyncRequest object at 0x7ffb7ffc9b38>
<grequests.AsyncRequest object at 0x7ffb7b9bdc18>
```

how do I write all response.text into single text file?
#### and, maybe you guys should write more document?

:smile:

**Comment by treilly** [comment]
Hi 1c7 - I'm new to this too but as far as I can tell, what you have is an unexecuted list of AsyncRequests which, since they haven't executed won't have responses or associated text.

To run them, add a line like:
`responses = grequests.map(rs)`

`responses` will then be a list of request.Response objects provided they were all successful.

For the use-case you describe you can then iterate through your responses and grab the `response.text` property and write it to a file

**Comment by 1c7** [comment]
@treilly Thanks!
