### ISSUE TITLE
use grequests in Flask with strange error

### ISSUE THREAD

**Issue by pengyusong** [kennethreitz/grequests#99]
i‘ import grequests in flask blueprints, because i want send multi requests in one http request of flask. but i encountered a problem:
 
> eventpoll fd will be increased for every http request, even if the http request does not use grequests.

I use ‘strace -p’ to get something deeply:

> Compared with normal  case, it add two ‘fcntl ‘ system call, they change the socket type to O_NONBLOCK.

it shows as follows:
`accept(3, {sa_family=AF_INET, sin_port=htons(58226), sin_addr=inet_addr("192.168.1.14")}, [16]) = 9
fcntl(9, F_GETFL)                       = 0x2 (flags O_RDWR)
fcntl(9, F_SETFL, O_RDWR|O_NONBLOCK)    = 0`

Notice:
i use werkzeug server to start flask will raise up this problem, if i use uwsgi etc. the problem will not occur.

questions:
1. dose grequests lib will infect outside socket(flask) ?
2. if above answer is true, how to avoid it?

**Comment by spyoungtech** [comment]
Because of the monkey-patching, importing `grequests` does end up potentially touching, and potentially breaking lot of other libraries. There are a number of other related issues that have been opened in the same light. Perhaps one of those may contain a clue to a possible solution. It would likely take a lot of effort to get down to the bottom of the cause, let alone a solution.

In my experience `grequests` works great in many cases. But if it doesn't work for your particular case, you may want to consider using, as the README now suggests, [requests-threads](https://github.com/requests/requests-threads) or [requests-futures](https://github.com/requests/requests-threads) instead.
